#15-Search bar
joao-pedrozo/shoppingify-client pull request #20
Opened 2023-04-04 02:44 UTC by renatarko

created search bar and added on MainScreen component - Issue#15

2023-04-04 13:45 UTC, tgmarinho approved these changes

2023-04-06 14:52 UTC, brunocroh requested changes

2023-04-06 14:52 UTC, brunocroh commented on src/components/SearchBar/index.tsx
> +            fontSize: 15,
Change de values to be equal to figma

```suggestion
            color: '#BDBDBD',
            fontSize: 14,
```

2023-04-06 14:52 UTC, brunocroh commented on src/components/SearchBar/index.tsx
> +          bg={'rgba(255, 255, 255, 1)'}
Change to HEX color please

2023-04-06 14:52 UTC, brunocroh commented on src/components/SearchBar/index.tsx
> +    <Flex m="1.6rem 4rem">
Change these units to px

2023-04-06 14:54 UTC, brunocroh commented
I merged another PR, and a conflict appear, you can resolve these for us?

You did a great job @renatarko!

2023-04-09 16:13 UTC, brunocroh approved these changes

2023-04-09 16:18 UTC, brunocroh commented
I wil merge it, thanks @renatarko !

2023-04-09 16:18 UTC, merged